### ISSUE TITLE
Exception in module.traefik_alb_auth_appreg.null_resource.no_aad_access_appreg_key

### ISSUE THREAD

**Issue by abstrask** [dfds/infrastructure-modules#55]
(At least) two problems:

1. Script shouldn't be failing
2. If it does, shouldn't Terraform fail as well? It *could* be that after the exception, the script handles the situation gracefully, but it needs investigation

```
Destroying... (ID: 7018381166559933817)
Destruction complete after 0s
Creating...
Provisioning with 'local-exec'...
Executing: ["/bin/sh" "-c" "/__w/30/s/oxygen-account/eu-west-1/k8s-hellman/services/.terragrunt-cache/XMlRoUdDcNcBDVjxV0McURkYWBA/zpsdurxmOhTALnA4xJU_txutyng/compute/k8s-services/.terraform/modules/1eb1179e1ea9cda9610abab2c6b1639b/create_key.sh 72c4e35b-b5f4-49e2-b3cc-4606932a2eba s3://dfds-core-terraform-state/keys/eks/hellman/appreg_alb_key.json"]
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'cloud'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/cloud.py", line 240, in get_active_cloud_name
    return cli_ctx.config.config_parser.get('cloud', 'name')
  File "/opt/az/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/opt/az/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'cloud'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 32, in <module>
    az_cli = get_default_cli()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 515, in get_default_cli
    help_cls=AzCliHelp)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    self.cloud = get_active_cloud(self)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/cloud.py", line 305, in get_active_cloud
    return get_cloud(cli_ctx, get_active_cloud_name(cli_ctx))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/cloud.py", line 242, in get_active_cloud_name
    _set_active_cloud(cli_ctx, AZURE_PUBLIC_CLOUD.name)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/cloud.py", line 235, in _set_active_cloud
    cli_ctx.config.set_value('cloud', 'name', cloud_name)
  File "/opt/az/lib/python3.6/site-packages/knack/config.py", line 95, in set_value
    self.set(config)
  File "/opt/az/lib/python3.6/site-packages/knack/config.py", line 82, in set
    with open(self.config_path, 'w') as configfile:
PermissionError: [Errno 13] Permission denied: '/home/ubuntu_azpcontainer/.azure/config'
/__w/30/s/oxygen-account/eu-west-1/k8s-hellman/services/.terragrunt-cache/XMlRoUdDcNcBDVjxV0McURkYWBA/zpsdurxmOhTALnA4xJU_txutyng/compute/k8s-services/.terraform/modules/1eb1179e1ea9cda9610abab2c6b1639b/create_key.sh: 14: [: -eq: unexpected operator
Not generating key.
Creation complete after 1s (ID: 8818090398194056666)
```

**Comment by avnes** [comment]
@abstrask It looks like the logic in module.traefik_alb_auth_appreg has changed so a null_resource is no longer used. Can we close this issue now?
